# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.4
      with:
        includePrerelease: true
        versionSpec: '5.3.x'
    - name: Use GitVersion
      id: gitversion # step id used as reference for output values     
      uses: gittools/actions/gitversion/execute@v0.9.4      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.0
    # Runs a set of commands using the runners shell
    - name: NPM scripts
      run: |
        npm install
        npm version --no-git-tag-version $GitVersion_SemVer
        npm build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
          # Artifact name
        name: webpack-output # optional
    # A file, directory or wildcard pattern that describes what to upload
        path: dist/
  deploy:
    if: ${{ false }} #github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: path/to/artifact
